openapi: 3.0.0
info:
    title: test-case-api
    version: 1.0.0
servers:
    - url: /
components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
paths:
    /auth/sign-in:
        post:
            tags:
                - authentication
            summary: sign-in
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            example:
                                email: admin@mail.com
                                password: admin
            responses:
                "200":
                    description: Successful response
                    content:
                        application/json: {}
    /auth/refresh:
        post:
            tags:
                - authentication
            summary: refresh
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            example:
                                refreshToken: b33f1ab7-e73c-409b-8908-6d3bda7e31af
            security:
                - bearerAuth: []
            responses:
                "200":
                    description: Successful response
                    content:
                        application/json: {}
    /auth/sign-out:
        post:
            tags:
                - authentication
            summary: sign-out
            requestBody:
                content: {}
            security:
                - bearerAuth: []
            responses:
                "200":
                    description: Successful response
                    content:
                        application/json: {}
    /users/1:
        patch:
            tags:
                - users
            summary: change user
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            example:
                                firstName: test
                                lastName: Журалев
                                email: admin@mail.com
                                password: admin
            security:
                - bearerAuth: []
            responses:
                "200":
                    description: Successful response
                    content:
                        application/json: {}
    /users/current:
        get:
            tags:
                - users
            summary: current
            security:
                - bearerAuth: []
            responses:
                "200":
                    description: Successful response
                    content:
                        application/json: {}
    /messages:
        get:
            tags:
                - messages
            summary: messages
            security:
                - bearerAuth: []
            parameters:
                - name: pageNumber
                  in: query
                  schema:
                      type: integer
                  required: true
                  example: 1
                - name: pageSize
                  in: query
                  schema:
                      type: integer
                  required: true
                  example: 10
                - name: isRead
                  in: query
                  schema:
                      type: boolean
                  example: "true"
                - name: isNew
                  in: query
                  schema:
                      type: boolean
                  example: "false"
                - name: reaction
                  in: query
                  schema:
                      type: string
                  example: negative
                - name: platformCode
                  in: query
                  schema:
                      type: string
                  example: ok
                - name: dateFrom
                  in: query
                  schema:
                      type: string
                  example: "2023-02-19T20:33:06.193Z"
                - name: dateTo
                  in: query
                  schema:
                      type: string
                  example: "2023-02-19T20:33:06.193Z"
                - name: search
                  in: query
                  schema:
                      type: string
                  example: test
                - name: sortingField
                  in: query
                  schema:
                      type: string
                  example: title
            responses:
                "200":
                    description: Successful response
                    content:
                        application/json: {}
    /messages/1:
        get:
            tags:
                - messages
            summary: http://localhost:3001/messages/1
            security:
                - bearerAuth: []
            responses:
                "200":
                    description: Successful response
                    content:
                        application/json: {}
        patch:
            tags:
                - messages
            summary: http://localhost:3001/messages/1
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            example:
                                isNew: false
            security:
                - bearerAuth: []
            responses:
                "200":
                    description: Successful response
                    content:
                        application/json: {}
